### ISSUE TITLE
Deploy Error: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by rbjoshi** [jagdish-176/serverless-nested-stack#13]
I have installed the ServerlessNestedPlugin and while deploying, I am getting the below error.

> TypeError: Cannot read property '0' of undefined
>       at ServerlessNestedPlugin.addPermissionParameters (/opt/atlassian/pipelines/agent/build/node_modules/serverless-nested-stack/index.js:229:84)
>       at ServerlessNestedPlugin.splitStack (/opt/atlassian/pipelines/agent/build/node_modules/serverless-nested-stack/index.js:78:14)
>       at /opt/atlassian/pipelines/agent/build/node_modules/serverless/lib/classes/PluginManager.js:490:55
>       at tryCatcher (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/util.js:16:23)
>       at Object.gotValue (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/reduce.js:168:18)
>       at Object.gotAccum (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/reduce.js:155:25)
>       at Object.tryCatcher (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/util.js:16:23)
>       at Promise._settlePromiseFromHandler (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/promise.js:547:31)
>       at Promise._settlePromise (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/promise.js:604:18)
>       at Promise._settlePromiseCtx (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/promise.js:641:10)
>       at _drainQueueStep (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/async.js:97:12)
>       at _drainQueue (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/async.js:86:9)
>       at Async._drainQueues (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/async.js:102:5)
>       at Immediate.Async.drainQueues [as _onImmediate] (/opt/atlassian/pipelines/agent/build/node_modules/bluebird/js/release/async.js:15:14)
>       at processImmediate (internal/timers.js:439:21)
>       at process.topLevelDomainCallback (domain.js:130:23)

****Version****
Node Version:              12.14.1
Framework Version:         1.61.3
Plugin Version:            3.2.7
SDK Version:               2.3.0
Components Core Version:   1.1.2
Components CLI Version:    1.4.0

serverless.yml snippet
```
plugins:
  - serverless-plugin-warmup
  - serverless-offline
  - serverless-log-forwarding
  - serverless-domain-manager
  - serverless-nested-stack
```

Need some insight, what am I missing here?

**Comment by allens01** [comment]
I am also experiencing this problem, did you manage to solve it @rbjoshi ?
